name: Jest Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '25'
        
    - name: Install dependencies
      run: |
        npm i
        cd server
        npm i
        cd ../client
        npm i
    
    - name: Create server env file
      run: |
        echo "PORT=8000" >> server/.env
        echo "HTTPS_KEY_PASSPHRASE=${{ secrets.HTTPS_KEY_PASSPHRASE }}" >> server/.env
        echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" >> server/.env
        echo "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY }}" >> server/.env
        echo "SUPABASE_TEST_AUTH_TOKEN=${{ secrets.SUPABASE_TEST_AUTH_TOKEN }}" >> server/.env
        
    - name: Create server https keys
      run: |
        echo "${{ secrets.TEST_KEY }}" > server/key.pem
        echo "${{ secrets.TEST_CERT }}" > server/cert.pem

    - name: Create client env file
      run: |
        echo "VITE_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" >> client/.env
        echo "VITE_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY }}" >> client/.env

    - name: Run server tests
      run: |
        cd server
        npm run test

    - name: Run client tests
      run: |
        cd client
        npm run test
