name: Jest Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '25'

    - name: Start server tests
      run: cd server
    
    - name: Create env file
      run: |
        echo "PORT=8000" >> .env
        echo "HTTPS_KEY_PASSPHRASE=${{ secrets.HTTPS_KEY_PASSPHRASE }}" >> .env
        echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" >> .env
        echo "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY }}" >> .env
        echo "SUPABASE_TEST_AUTH_TOKEN=${{ secrets.SUPABASE_TEST_AUTH_TOKEN }}" >> .env
        
    - name: Create https keys
      run: |
        echo "${{ secrets.testKey }}" > key.pem
        echo "${{ secrets.testCert }}" > cert.pem
    
    - name: Install server dependencies
      run: npm i

    - name: Run server tests
      run: npm run test
