name: Jest Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Build client static page
      uses: actions/setup-node@v4
      with:
        node-version: '25'

    - name: Create client env file
      run: |
        echo "VITE_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" >> client/.env
        echo "VITE_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY }}" >> client/.env
        echo "VITE_SERVER_URL=https://placeholder.url" >> client/.env

    - name: Build vite page
      run: |
        cd client
        npm install
        npm run build

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '25'
        
    - name: Install dependencies
      run: |
        npm install
        cd server
        npm install
        cd ../client
        npm install
    
    - name: Create server env file
      run: |
        echo "PORT=8000" >> server/.env
        echo "HTTPS_KEY_PASSPHRASE=${{ secrets.HTTPS_KEY_PASSPHRASE }}" >> server/.env
        echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" >> server/.env
        echo "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY }}" >> server/.env
        echo "COOKIE_HOST_URL=.localhost" >> server/.env
        
    - name: Import server https keys
      run: |
        echo "${{ secrets.TEST_KEY }}" > server/key.pem
        echo "${{ secrets.TEST_CERT }}" > server/cert.pem

    - name: Create client env file
      run: |
        echo "VITE_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" >> client/.env
        echo "VITE_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY }}" >> client/.env
        echo "VITE_SERVER_URL=https://localhost:8000" >> client/.env
        echo "VITE_COOKIE_HOST_URL=.localhost" >> client/.env

    - name: Run server tests
      run: |
        cd server
        npm run test

    - name: Run client tests
      run: |
        cd client
        npm run test
    
    - name: Run integration tests
      run: |
        npx start-server-and-test 'npm run dev' http://localhost:5173 'npx cypress run'
